#!/usr/bin/expect
# set readings(DEVICE) { reading1 reading2 reading3 }
set readings(OBIS_hausstromzaehler) { total_consumption total_feed }
set readings(OBIS_waermestromzaehler) { thotal_consumption total_consumption_Ch1 total_consumption_Ch2 }
