#!/usr/bin/expect
# set readings(DEVICE) { reading1 reading2 reading3 }
set readings(solix2mqtt) { scenInfo_home_load_power scenInfo_solarbank_info_solarbank_list_1_photovoltaic_power scenInfo_solarbank_info_solarbank_list_1_battery_power scenInfo_solarbank_info_solar_power_1 scenInfo_solarbank_info_solar_power_2 scenInfo_solarbank_info_solar_power_3 scenInfo_solarbank_info_solar_power_4 scenInfo_solarbank_info_solarbank_list_1_output_power }
